// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatBytes(arg1) {
  return window['go']['main']['App']['FormatBytes'](arg1);
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function PeerReceive(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PeerReceive'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartPeerSend(arg1, arg2) {
  return window['go']['main']['App']['StartPeerSend'](arg1, arg2);
}

export function StopPeerSend() {
  return window['go']['main']['App']['StopPeerSend']();
}
