// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transfer} from '../models';

export function FormatBytes(arg1:number):Promise<string>;

export function GetFileInfo(arg1:string):Promise<transfer.FileInfo>;

export function GetLocalServerURL():Promise<string>;

export function PeerReceive(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ReceiveFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendFile(arg1:string,arg2:string,arg3:number,arg4:number):Promise<transfer.SendResult>;

export function StartPeerSend(arg1:string,arg2:number):Promise<transfer.PeerInfo>;

export function StopPeerSend():Promise<void>;
